# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2055379a1ce4d11a8cee8dfffa428180359a354c8f865ebd57f456d79469d9e12fd9bc1b7f3bdf438f8795cdd290c1c3c36731700e96806dbe9c2b00ab99818

test:
  secret_key_base: e73a932dd0b0a9815f53a2dc689d8023a6381ebe8bea12866c6bca05388d2a48adaaadf05b5bb9f9854d664c6eec01d15b8d7345b379e2c959ce6e68742aeb12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
